import {
  StylBoxBtnPatients,
  StylBoxColumn,
  StylBoxColumnFlex,
  StylBoxDoctor,
  StylBoxFlexColumn,
  StylBoxForm,
  StylBoxFormSignIn,
  StylBoxImgInfo,
  StylBoxPatientContent,
  StylBoxPatients,
  StylBoxPatientsList,
  StylBoxRow,
  StylBoxRowFlexStart,
  StylBoxRowPadding,
  StylBoxRowMargin,
  StylBoxSelect,
  StylBoxViewContent,
  StylBoxMain,
} from './Boxes.styled';

export {
  StylBoxMain,
  StylBoxBtnPatients,
  StylBoxColumn,
  StylBoxColumnFlex,
  StylBoxDoctor,
  StylBoxFlexColumn,
  StylBoxForm,
  StylBoxFormSignIn,
  StylBoxImgInfo,
  StylBoxPatientContent,
  StylBoxPatients,
  StylBoxPatientsList,
  StylBoxRow,
  StylBoxRowFlexStart,
  StylBoxRowPadding,
  StylBoxRowMargin,
  StylBoxSelect,
  StylBoxViewContent,
};
